// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web3Multitool.EntityFramework;

#nullable disable

namespace Web3Multitool.EntityFramework.Migrations
{
    [DbContext(typeof(AccountInfoDbContext))]
    [Migration("20230605164627_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3");

            modelBuilder.Entity("Web3Multitool.EntityFramework.DTOs.AccountInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArbitrumInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvaxInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CexAddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("FantomInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OptimismInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PolygonInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalBalanceUsd")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalTxAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArbitrumInfoId");

                    b.HasIndex("AvaxInfoId");

                    b.HasIndex("FantomInfoId");

                    b.HasIndex("OptimismInfoId");

                    b.HasIndex("PolygonInfoId");

                    b.ToTable("AccountInfo");
                });

            modelBuilder.Entity("Web3Multitool.EntityFramework.DTOs.AddressChainInfoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BaseBalance")
                        .HasColumnType("REAL");

                    b.Property<int>("ChainId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstTxDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TxAmount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UsdcBalance")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("AddressChainInfos");
                });

            modelBuilder.Entity("Web3Multitool.EntityFramework.DTOs.AccountInfoDto", b =>
                {
                    b.HasOne("Web3Multitool.EntityFramework.DTOs.AddressChainInfoDto", "ArbitrumInfo")
                        .WithMany()
                        .HasForeignKey("ArbitrumInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web3Multitool.EntityFramework.DTOs.AddressChainInfoDto", "AvaxInfo")
                        .WithMany()
                        .HasForeignKey("AvaxInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web3Multitool.EntityFramework.DTOs.AddressChainInfoDto", "FantomInfo")
                        .WithMany()
                        .HasForeignKey("FantomInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web3Multitool.EntityFramework.DTOs.AddressChainInfoDto", "OptimismInfo")
                        .WithMany()
                        .HasForeignKey("OptimismInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web3Multitool.EntityFramework.DTOs.AddressChainInfoDto", "PolygonInfo")
                        .WithMany()
                        .HasForeignKey("PolygonInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArbitrumInfo");

                    b.Navigation("AvaxInfo");

                    b.Navigation("FantomInfo");

                    b.Navigation("OptimismInfo");

                    b.Navigation("PolygonInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
